// Datos del catálogo de proyectos frontend.
// Fuente única de verdad para el renderizado de la cuadrícula y los filtros.

export const categories = [
  { id: "todos", label: "Todos" },
  { id: "componentes", label: "Componentes" },
  { id: "aplicaciones", label: "Aplicaciones" },
  { id: "formularios", label: "Formularios" },
  { id: "errores", label: "Errores" },
  { id: "layout", label: "Layout" },
];

// Ciclo de acentos por tarjeta (galería de cambio de color del tema Hum).
export const accents = ["pear", "cyan", "coral", "mint", "lav"];

export const projects = [
  {
    slug: "calificacion-estrellas",
    name: "Calificación de estrellas",
    category: "componentes",
    categoryLabel: "Componente",
    description: "Valoración de cinco estrellas interactivas para reseñas.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/calificacion-estrellas/icon/estrella-llena.png",
    entry: "catalog/calificacion-estrellas/index.html",
    zip: "catalog/calificacion-estrellas.zip",
  },
  {
    slug: "drop-down",
    name: "Menú desplegable",
    category: "componentes",
    categoryLabel: "Componente",
    description: "Menú desplegable con animación de apertura.",
    tech: ["HTML", "CSS"],
    icon: "catalog/drop-down/icon/icono.png",
    entry: "catalog/drop-down/index.html",
    zip: "catalog/drop-down.zip",
  },
  {
    slug: "error-http-403",
    name: "Error 403",
    category: "errores",
    categoryLabel: "Error",
    description: "Pantalla de acceso denegado con estilo propio.",
    tech: ["HTML", "CSS"],
    icon: "catalog/error-http-403/icon/error-403.png",
    entry: "catalog/error-http-403/index.html",
    zip: "catalog/error-http-403.zip",
  },
  {
    slug: "error-http-404",
    name: "Error 404",
    category: "errores",
    categoryLabel: "Error",
    description: "Página no encontrada con ilustración y vuelta al inicio.",
    tech: ["HTML", "CSS"],
    icon: "catalog/error-http-404/icon/error-404.png",
    entry: "catalog/error-http-404/index.html",
    zip: "catalog/error-http-404.zip",
  },
  {
    slug: "error-http-405",
    name: "Error 405",
    category: "errores",
    categoryLabel: "Error",
    description: "Mensaje de método no permitido.",
    tech: ["HTML", "CSS"],
    icon: "catalog/error-http-405/icon/error-405.png",
    entry: "catalog/error-http-405/index.html",
    zip: "catalog/error-http-405.zip",
  },
  {
    slug: "footer",
    name: "Pie de página",
    category: "componentes",
    categoryLabel: "Componente",
    description: "Pie de página con enlaces y suscripción.",
    tech: ["HTML", "CSS"],
    icon: "catalog/footer/icon/logo.png",
    entry: "catalog/footer/index.html",
    zip: "catalog/footer.zip",
  },
  {
    slug: "fryfly-prototipo",
    name: "FryFly",
    category: "aplicaciones",
    categoryLabel: "Aplicación",
    description: "Prototipo multi-pantalla de una app de comida rápida.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/fryfly-prototipo/ICONS/logo.png",
    entry: "catalog/fryfly-prototipo/HTML/presentacion.html",
    zip: "catalog/fryfly-prototipo.zip",
  },
  {
    slug: "gestor-archivos-demo",
    name: "Gestor de archivos",
    category: "aplicaciones",
    categoryLabel: "Aplicación",
    description: "Demo de gestor de archivos con secciones y búsqueda.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/gestor-archivos-demo/icon/carpeta.png",
    entry: "catalog/gestor-archivos-demo/index.html",
    zip: "catalog/gestor-archivos-demo.zip",
  },
  {
    slug: "inicio-sesion-registro",
    name: "Inicio de sesión y registro",
    category: "formularios",
    categoryLabel: "Formulario",
    description: "Formularios de inicio de sesión y de registro.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/inicio-sesion-registro/image/inicio.png",
    entry: "catalog/inicio-sesion-registro/index.html",
    zip: "catalog/inicio-sesion-registro.zip",
  },
  {
    slug: "inicio-sesion-verificacion",
    name: "Sesión con verificación",
    category: "formularios",
    categoryLabel: "Formulario",
    description: "Inicio de sesión con verificación mediante captcha.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/inicio-sesion-verificacion/icon/login.png",
    entry: "catalog/inicio-sesion-verificacion/index.html",
    zip: "catalog/inicio-sesion-verificacion.zip",
  },
  {
    slug: "lista-tareas",
    name: "Lista de tareas",
    category: "aplicaciones",
    categoryLabel: "Aplicación",
    description: "Aplicación de tareas para añadir y completar pendientes.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/lista-tareas/icon/icono.png",
    entry: "catalog/lista-tareas/index.html",
    zip: "catalog/lista-tareas.zip",
  },
  {
    slug: "menu-acordeon",
    name: "Menú acordeón",
    category: "componentes",
    categoryLabel: "Componente",
    description: "Menú acordeón con secciones expandibles.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/menu-acordeon/icon/acordeon.png",
    entry: "catalog/menu-acordeon/index.html",
    zip: "catalog/menu-acordeon.zip",
  },
  {
    slug: "modal",
    name: "Ventana modal",
    category: "componentes",
    categoryLabel: "Componente",
    description: "Ventana modal con fondo oscurecido.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/modal/icon/modal.png",
    entry: "catalog/modal/index.html",
    zip: "catalog/modal.zip",
  },
  {
    slug: "modo-claro-oscuro",
    name: "Modo claro / oscuro",
    category: "componentes",
    categoryLabel: "Componente",
    description: "Alternancia entre tema claro y oscuro.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/modo-claro-oscuro/icon/oscuro.png",
    entry: "catalog/modo-claro-oscuro/index.html",
    zip: "catalog/modo-claro-oscuro.zip",
  },
  {
    slug: "pagina-responsive",
    name: "Página responsive",
    category: "layout",
    categoryLabel: "Layout",
    description: "Página de ejemplo con diseño adaptativo.",
    tech: ["HTML", "CSS"],
    icon: "catalog/pagina-responsive/icon/pagina-responsive.png",
    entry: "catalog/pagina-responsive/index.html",
    zip: "catalog/pagina-responsive.zip",
  },
  {
    slug: "panel-control",
    name: "Panel de control",
    category: "aplicaciones",
    categoryLabel: "Aplicación",
    description: "Panel de control con tarjetas y métricas.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/panel-control/icon/panelControl.png",
    entry: "catalog/panel-control/index.html",
    zip: "catalog/panel-control.zip",
  },
  {
    slug: "side-bar",
    name: "Barra lateral",
    category: "componentes",
    categoryLabel: "Componente",
    description: "Barra lateral de navegación colapsable.",
    tech: ["HTML", "CSS", "JS"],
    icon: "catalog/side-bar/icon/carpeta.png",
    entry: "catalog/side-bar/index.html",
    zip: "catalog/side-bar.zip",
  },
];
